framework:
    messenger:
        failure_transport: failed_default

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration

            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_DOCKER)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
                failure_transport: failed_high_priority

            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            failed_default: 'doctrine://default?queue_name=failed_default'
            failed_high_priority:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_DOCKER)%'
                options:
                    exchange:
                        name: registration_email_failed
                    queues:
                        registration_email_failed: ~
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async_priority_high
            Symfony\Component\Notifier\Message\ChatMessage: async_priority_high
            Symfony\Component\Notifier\Message\SmsMessage: async_priority_high
            App\Message\SampleMessage: async_priority_high
            App\Security\EmailVerifier: async_priority_high

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
