
services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      DATABASE_URL: mysql://root@database:3306/${MYSQL_DATABASE}
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN_DOCKER}
      MAILER_DSN: ${MAILER_DSN_DOCKER}
      MAIL_ENCRYPTION: tls
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
        mode: host
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    cap_add:
      - NET_BIND_SERVICE
  ###> doctrine/doctrine-bundle ###
  database:  
    image: mysql:8
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - 3307:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 40s
        retries: 5
        start_period: 120s
    volumes:
     - ./docker/db/data:/var/lib/mysql:rw
  ###< doctrine/doctrine-bundle ###
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - '5672:5672'
      - '15672:15672'
  
  jmeter:
    image: justb4/jmeter
    volumes:
      - ./tests/opt:/tests/opt
    command: -n -t /tests/opt/test.jmx -l /tests/opt/results.jtl

volumes:
  caddy_data:
  caddy_config: