
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
      - ./logs:/var/log/frankenphp:rw
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true

###> fail2ban ###
  fail2ban:
      build:
        context: ./fail2ban
        target: fail2ban_base
      network_mode: host
      cap_add:
        - NET_ADMIN
        - NET_RAW
      volumes:
        - ./logs:/var/log/frankenphp:rw
        - ./fail2ban/data:/data
      restart: on-failure
###< fail2ban ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./mailer:/data
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

volumes:
  logs: